spring.application.name=storybox
spring.profiles.default=dev

management.endpoints.web.exposure.include=health, info, metrics, env, loggers
management.endpoint.health.show-details=always

server.port=8080

logging.level.com.storybox=INFO
logging.level.com.pi4j=WARN
logging.level.com.storybox.storybox.story=INFO

storybox.audio.player=mpv
storybox.audio.default-track=fallback.mp3
storybox.audio.library-dir=/audio

storybox.gpio.enabled=false
storybox.gpio.clk-pin=22
storybox.gpio.dt-pin=27
storybox.gpio.sw-pin=17

storybox.story.pack=classpath:stories.json

#spring.ai.model.chat=ollama

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.init.pull-model-strategy=never

# Thaura AI
spring.ai.openai.base-url=https://backend.thaura.ai
spring.ai.openai.api-key=${THAURA_API_KEY}
spring.ai.openai.chat.options.model=thaura
spring.ai.openai.chat.options.temperature=0.7